// English -> Bangla extras (UI messages, products, categories, brands, areas, reviews). Merged into PHRASES by bnPhrases.js.
// Add one line  "English text": "বাংলা"  here for any new text.
export const MORE = {
 "Fresh Organic Market": "ফ্রেশ অর্গানিক মার্কেট",
 "Freshly": "ফ্রেশলি",
 "loading…": "লোড হচ্ছে…",
 "Your orders": "আপনার অর্ডার",
 "No orders yet. Your orders and their tracking will show here.": "এখনও কোনো অর্ডার নেই। আপনার অর্ডার ও ট্র্যাকিং এখানে দেখা যাবে।",
 "Reorder": "আবার অর্ডার",
 "Reorder all": "সব আবার অর্ডার করুন",
 "Please enter your name.": "অনুগ্রহ করে আপনার নাম লিখুন।",
 "Enter a valid email address, e.g. name@example.com.": "সঠিক ইমেইল ঠিকানা দিন, যেমন name@example.com।",
 "Password must be at least 6 characters.": "পাসওয়ার্ড কমপক্ষে ৬ অক্ষরের হতে হবে।",
 "Create your account": "আপনার অ্যাকাউন্ট তৈরি করুন",
 "Browse as a guest anytime. Log in to add items, save favourites and order.": "যেকোনো সময় অতিথি হিসেবে ঘুরে দেখুন। পণ্য যোগ, পছন্দ সংরক্ষণ ও অর্ডার করতে লগইন করুন।",
 "Email address": "ইমেইল ঠিকানা",
 "Password (min 6 characters)": "পাসওয়ার্ড (কমপক্ষে ৬ অক্ষর)",
 "Please wait…": "অনুগ্রহ করে অপেক্ষা করুন…",
 "New here?": "নতুন এসেছেন?",
 "Already have an account?": "আগে থেকেই অ্যাকাউন্ট আছে?",
 "Create an account": "অ্যাকাউন্ট খুলুন",
 "Continue as guest": "অতিথি হিসেবে চালিয়ে যান",
 "Close cart": "কার্ট বন্ধ করুন",
 "Your cart is empty. Add something fresh.": "আপনার কার্ট খালি। তাজা কিছু যোগ করুন।",
 "Not applicable now. Minimum order": "এখন প্রযোজ্য নয়। সর্বনিম্ন অর্ডার",
 "Enter": "দিন",
 "Coupon code (try FRESH10)": "কুপন কোড (FRESH10 চেষ্টা করুন)",
 "Checkout ·": "চেকআউট ·",
 "Could not save the address.": "ঠিকানা সংরক্ষণ করা যায়নি।",
 "We could not place your order. Please try again.": "আপনার অর্ডার দেওয়া যায়নি। আবার চেষ্টা করুন।",
 "pending confirmation": "নিশ্চিতকরণের অপেক্ষায়",
 "Express +": "এক্সপ্রেস +",
 "Express is not available in this delivery area.": "এই ডেলিভারি এলাকায় এক্সপ্রেস পাওয়া যাবে না।",
 "Express orders arrive": "এক্সপ্রেস অর্ডার পৌঁছায়",
 "within ~90 minutes": "~৯০ মিনিটের মধ্যে",
 "Delivery time ·": "ডেলিভারির সময় ·",
 "Fully booked": "সব বুক হয়ে গেছে",
 "Time has passed": "সময় পেরিয়ে গেছে",
 "Free delivery is for Standard delivery": "ফ্রি ডেলিভারি শুধু স্ট্যান্ডার্ড ডেলিভারির জন্য",
 "You get free delivery": "আপনি ফ্রি ডেলিভারি পাচ্ছেন",
 "Close cart bar": "কার্ট বার বন্ধ করুন",
 "Fastest Delivery": "দ্রুততম ডেলিভারি",
 "Delivery to your door step": "আপনার দোরগোড়ায় ডেলিভারি",
 "24x7 Service": "২৪/৭ সেবা",
 "Reach us when needed": "প্রয়োজনে যোগাযোগ করুন",
 "Verified Brands": "যাচাইকৃত ব্র্যান্ড",
 "Guaranteed products": "নিশ্চিত মানের পণ্য",
 "100% Assurance": "১০০% নিশ্চয়তা",
 "We stand by every order": "প্রতিটি অর্ডারের দায়িত্ব আমাদের",
 "Customer support": "গ্রাহক সহায়তা",
 "Fresh groceries delivered to your door step, anywhere in Bangladesh.": "বাংলাদেশের যেকোনো জায়গায় আপনার দোরগোড়ায় তাজা মুদি পণ্য।",
 "We accept": "আমরা গ্রহণ করি",
 "© 2026 Freshly. All rights reserved.": "© ২০২৬ ফ্রেশলি। সর্বস্বত্ব সংরক্ষিত।",
 "· Express available": "· এক্সপ্রেস পাওয়া যাবে",
 "Could not save.": "সংরক্ষণ করা যায়নি।",
 "New password must be at least 6 characters.": "নতুন পাসওয়ার্ড কমপক্ষে ৬ অক্ষরের হতে হবে।",
 "The two new passwords do not match.": "দুটি নতুন পাসওয়ার্ড মিলছে না।",
 "Could not change the password.": "পাসওয়ার্ড পরিবর্তন করা যায়নি।",
 "Could not delete.": "মুছে ফেলা যায়নি।",
 "2–4 days": "২–৪ দিন",
 "Return requested ·": "রিটার্নের অনুরোধ করা হয়েছে ·",
 "? This cannot be undone.": "? এটি ফেরানো যাবে না।",
 "Cancel order": "অর্ডার বাতিল",
 "No products found. Try another search or tab.": "কোনো পণ্য পাওয়া যায়নি। অন্য সার্চ বা ট্যাব চেষ্টা করুন।",
 "No reviews yet": "এখনও কোনো রিভিউ নেই",
 "Please log in to write a review.": "রিভিউ লিখতে লগইন করুন।",
 "Could not save your review. Please try again.": "আপনার রিভিউ সংরক্ষণ করা যায়নি। আবার চেষ্টা করুন।",
 "✓ You bought this product, so your review will show a “Verified purchase” badge.": "✓ আপনি এই পণ্যটি কিনেছেন, তাই আপনার রিভিউতে “যাচাইকৃত ক্রয়” ব্যাজ দেখাবে।",
 "Please log in to vote on reviews.": "রিভিউতে ভোট দিতে লগইন করুন।",
 "Could not save your vote.": "আপনার ভোট সংরক্ষণ করা যায়নি।",
 "More from": "আরও পণ্য:",
 "(You)": "(আপনি)",
 "found this helpful": "জন এটি সহায়ক মনে করেছেন",
 "Unavailable": "অনুপলব্ধ",
 "Hover to zoom": "জুম করতে হোভার করুন",
 "Recommended for you": "আপনার জন্য সুপারিশ",
 "Popular picks": "জনপ্রিয় বাছাই",
 "Shop by brand": "ব্র্যান্ড অনুযায়ী কিনুন",
 "Shop by category": "ক্যাটাগরি অনুযায়ী কিনুন",
 "Top saver today": "আজকের সেরা সাশ্রয়",
 "Deals end in": "অফার শেষ হতে বাকি",
 "Your last order, back in your cart in one tap": "আপনার শেষ অর্ডার, এক ট্যাপে কার্টে",
 "Log in to see your last order and reorder it in one tap.": "আপনার শেষ অর্ডার দেখতে ও এক ট্যাপে আবার অর্ডার করতে লগইন করুন।",
 "Please log in to see your previous orders.": "আগের অর্ডার দেখতে লগইন করুন।",
 "No previous orders yet. Once you order, it will show up here.": "এখনও কোনো আগের অর্ডার নেই। অর্ডার করলে এখানে দেখা যাবে।",
 "Pick a dish, we add every ingredient": "একটি পদ বাছুন, আমরা সব উপকরণ যোগ করব",
 "Tick the ingredients you need": "যে উপকরণ লাগবে তাতে টিক দিন",
 "Hide ingredients ▲": "উপকরণ লুকান ▲",
 "Choose ingredients ▼": "উপকরণ বাছুন ▼",
 "Add all": "সব যোগ করুন",
 "(out of stock)": "(স্টকে নেই)",
 "Add selected (": "নির্বাচিত যোগ করুন (",
 "Recipe to cart": "রেসিপি থেকে কার্টে",
 "Search recipe or ingredient": "রেসিপি বা উপকরণ খুঁজুন",
 "No recipe found. Try an ingredient like “egg” or “mango”.": "কোনো রেসিপি পাওয়া যায়নি। “ডিম” বা “আম” এর মতো উপকরণ লিখে দেখুন।",
 "Recently viewed": "সম্প্রতি দেখা",
 "Pagination": "পৃষ্ঠা নেভিগেশন",
 "Previous page": "আগের পৃষ্ঠা",
 "Next page": "পরের পৃষ্ঠা",
 "Previous slide": "আগের স্লাইড",
 "Next slide": "পরের স্লাইড",
 "Your session expired. Please log in again.": "আপনার সেশন শেষ হয়েছে। আবার লগইন করুন।",
 "Could not load your cart.": "আপনার কার্ট লোড করা যায়নি।",
 "Please log in to add items to your cart.": "কার্টে পণ্য যোগ করতে লগইন করুন।",
 "Please log in to add these to your cart.": "এগুলো কার্টে যোগ করতে লগইন করুন।",
 "Please log in to reorder.": "আবার অর্ডার করতে লগইন করুন।",
 "Could not update wishlist": "উইশলিস্ট আপডেট করা যায়নি",
 "Please log in to save items to your wishlist.": "উইশলিস্টে সংরক্ষণ করতে লগইন করুন।",
 "Please log in to buy this item.": "এই পণ্যটি কিনতে লগইন করুন।",
 "Please log in to use a coupon.": "কুপন ব্যবহার করতে লগইন করুন।",
 "Could not load the store.": "দোকান লোড করা যায়নি।",
 "We couldn't load the store": "আমরা দোকান লোড করতে পারিনি",
 "Highest rating": "সর্বোচ্চ রেটিং",
 "Lowest rating": "সর্বনিম্ন রেটিং",
 "Time slots:": "সময় স্লট:",
 "10% off (max ৳200, min order ৳300)": "১০% ছাড় (সর্বোচ্চ ৳২০০, সর্বনিম্ন অর্ডার ৳৩০০)",
 "৳50 off (min order ৳500)": "৳৫০ ছাড় (সর্বনিম্ন অর্ডার ৳৫০০)",
 "Free delivery (min order ৳200)": "ফ্রি ডেলিভারি (সর্বনিম্ন অর্ডার ৳২০০)",
 "Please choose 1 to 5 stars.": "১ থেকে ৫ তারা বাছুন।",
 "Product not found.": "পণ্য পাওয়া যায়নি।",
 "Review not found.": "রিভিউ পাওয়া যায়নি।",
 "You can't vote on your own review.": "নিজের রিভিউতে ভোট দেওয়া যায় না।",
 "Enter a valid email address.": "সঠিক ইমেইল ঠিকানা দিন।",
 "This email is already registered. Please log in.": "এই ইমেইল আগেই নিবন্ধিত। লগইন করুন।",
 "Your current password is wrong.": "আপনার বর্তমান পাসওয়ার্ড ভুল।",
 "Address type must be Home or Office.": "ঠিকানার ধরন বাসা বা অফিস হতে হবে।",
 "This coupon code is not valid.": "এই কুপন কোডটি সঠিক নয়।",
 "A product in your cart is no longer available.": "আপনার কার্টের একটি পণ্য আর পাওয়া যাচ্ছে না।",
 "Please choose a delivery area.": "ডেলিভারি এলাকা বাছুন।",
 "Express delivery is not available in your area.": "আপনার এলাকায় এক্সপ্রেস ডেলিভারি পাওয়া যাবে না।",
 "Please enter your delivery address.": "ডেলিভারির ঠিকানা লিখুন।",
 "That delivery time slot is no longer available. Please pick another.": "ওই ডেলিভারি সময় আর খালি নেই। অন্য সময় বাছুন।",
 "Please choose a payment method.": "পেমেন্ট পদ্ধতি বাছুন।",
 "Order not found.": "অর্ডার পাওয়া যায়নি।",
 "This order is already packed and cannot be cancelled. Please call us.": "এই অর্ডার প্যাক হয়ে গেছে, বাতিল করা যাবে না। আমাদের ফোন করুন।",
 "Only delivered orders can be returned.": "শুধু ডেলিভারি হওয়া অর্ডার ফেরত দেওয়া যায়।",
 "A return was already requested for this order.": "এই অর্ডারের জন্য আগেই রিটার্নের অনুরোধ করা হয়েছে।",
 "Please choose a reason.": "একটি কারণ বাছুন।",
 "How do I order? Browse as a guest, log in when you add items, then check out from the cart.": "কীভাবে অর্ডার করব? অতিথি হিসেবে ঘুরে দেখুন, পণ্য যোগ করার সময় লগইন করুন, তারপর কার্ট থেকে চেকআউট করুন।",
 "Can I change my order? Call us on 09 4932 4782 before the status reaches \"Packed\".": "অর্ডার পরিবর্তন করা যাবে? স্ট্যাটাস “প্যাক হয়েছে” হওয়ার আগে আমাদের ০৯ ৪৯৩২ ৪৭৮২ নম্বরে ফোন করুন।",
 "Where is my order? Open My account > Your orders to see live tracking.": "আমার অর্ডার কোথায়? লাইভ ট্র্যাকিং দেখতে আমার অ্যাকাউন্ট > আপনার অর্ডার খুলুন।",
 "Phone: 09 4932 4782 (24x7)": "ফোন: ০৯ ৪৯৩২ ৪৭৮২ (২৪/৭)",
 "Email: support@freshly.example": "ইমেইল: support@freshly.example",
 "Tell us your order ID so we can help faster.": "দ্রুত সাহায্য করতে আমাদের আপনার অর্ডার আইডি জানান।",
 "DRAFT policy - confirm before launch.": "খসড়া নীতি - চালুর আগে নিশ্চিত করুন।",
 "Fresh items (vegetables, fruits, meat, fish, dairy): report any problem within 24 hours of delivery with a photo and we will replace or refund.": "তাজা পণ্য (সবজি, ফল, মাংস, মাছ, দুগ্ধজাত): ডেলিভারির ২৪ ঘণ্টার মধ্যে ছবিসহ সমস্যা জানালে আমরা বদলে দেব বা টাকা ফেরত দেব।",
 "Packaged items: unopened and unused items can be returned within 3 days.": "প্যাকেটজাত পণ্য: না খোলা ও অব্যবহৃত পণ্য ৩ দিনের মধ্যে ফেরত দেওয়া যাবে।",
 "Refunds go back to your original payment method (bKash / Nagad / card) or are adjusted on your next order for cash on delivery.": "রিফান্ড আপনার মূল পেমেন্ট মাধ্যমে (বিকাশ / নগদ / কার্ড) ফেরত যাবে, ক্যাশ অন ডেলিভারির ক্ষেত্রে পরবর্তী অর্ডারে সমন্বয় করা হবে।",
 "Freshly delivers fresh groceries to your door step, anywhere in Bangladesh.": "ফ্রেশলি বাংলাদেশের যেকোনো জায়গায় আপনার দোরগোড়ায় তাজা মুদি পণ্য পৌঁছে দেয়।",
 "We work with trusted farms and verified brands so every order is fresh and fairly priced.": "আমরা বিশ্বস্ত খামার ও যাচাইকৃত ব্র্যান্ডের সঙ্গে কাজ করি, যাতে প্রতিটি অর্ডার তাজা ও ন্যায্য দামের হয়।",
 "We are always looking for riders, packers and developers.": "আমরা সবসময় রাইডার, প্যাকার ও ডেভেলপার খুঁজছি।",
 "Send your CV to careers@freshly.example.": "আপনার সিভি পাঠান careers@freshly.example ঠিকানায়।",
 "We collect your name, mobile number, addresses and order history only to process and deliver your orders.": "আমরা আপনার নাম, মোবাইল নম্বর, ঠিকানা ও অর্ডারের ইতিহাস শুধু আপনার অর্ডার প্রক্রিয়া ও ডেলিভারির জন্য সংগ্রহ করি।",
 "We never sell your data. Payment details are handled by the payment provider, not stored by us.": "আমরা আপনার তথ্য কখনো বিক্রি করি না। পেমেন্টের তথ্য পেমেন্ট প্রদানকারী সামলায়, আমরা সংরক্ষণ করি না।",
 "DRAFT terms - confirm before launch.": "খসড়া শর্তাবলি - চালুর আগে নিশ্চিত করুন।",
 "Prices and availability can change. Your order is confirmed once you receive an order ID.": "দাম ও পণ্যের প্রাপ্যতা বদলাতে পারে। অর্ডার আইডি পেলে আপনার অর্ডার নিশ্চিত হয়।",
 "Delivery times are estimates. Free delivery and coupons follow the rules shown in the cart.": "ডেলিভারির সময় আনুমানিক। ফ্রি ডেলিভারি ও কুপন কার্টে দেখানো নিয়ম অনুযায়ী প্রযোজ্য।",
 "Fresh Today": "আজকের তাজা",
 "Only 3 Left": "মাত্র ৩টি আছে",
 "Near Expiry": "মেয়াদ শেষের কাছাকাছি",
 "Out of Stock": "স্টকে নেই",
 "Inside Sylhet City": "সিলেট সিটির ভেতরে",
 "Inside Dhaka City": "ঢাকা সিটির ভেতরে",
 "Dhaka Suburbs (Savar, Gazipur, Narayanganj)": "ঢাকার আশপাশ (সাভার, গাজীপুর, নারায়ণগঞ্জ)",
 "Outside Dhaka / All Bangladesh (Courier)": "ঢাকার বাইরে / সারা বাংলাদেশ (কুরিয়ার)",
 "9 – 11 AM": "সকাল ৯ – ১১টা",
 "11 AM – 1 PM": "সকাল ১১টা – দুপুর ১টা",
 "4 – 6 PM": "বিকাল ৪ – ৬টা",
 "6 – 8 PM": "সন্ধ্যা ৬ – ৮টা",
 "Grocery Shopping Made Fast, Easy & Affordable": "মুদি কেনাকাটা এখন দ্রুত, সহজ ও সাশ্রয়ী",
 "Eid special": "ঈদ স্পেশাল",
 "Feast Essentials": "ভোজের প্রয়োজনীয় সামগ্রী",
 "Glow week": "গ্লো উইক",
 "Beauty & Personal Care": "বিউটি ও পার্সোনাল কেয়ার",
 "Fresh harvest": "তাজা ফসল",
 "Fruits & Vegetables": "ফল ও সবজি",
 "Winter treats": "শীতের আয়োজন",
 "Snacks & Sweets": "স্ন্যাকস ও মিষ্টি",
 "Weekend Grocery Sale": "সাপ্তাহিক ছুটির গ্রোসারি সেল",
 "Grocery Combo Deals": "গ্রোসারি কম্বো অফার",
 "Eid Grocery Sale": "ঈদ গ্রোসারি সেল",
 "Eid & Puja Offer": "ঈদ ও পূজা অফার",
 "Eid-ul-Adha & Durga Puja Super Combo": "ঈদুল আযহা ও দুর্গাপূজা সুপার কম্বো",
 "Veggie Curry": "সবজির তরকারি",
 "Fruit Breakfast Bowl": "ফলের নাশতার বাটি",
 "Cheesy Omelette": "চিজ ওমলেট",
 "Chicken Curry & Rice": "চিকেন কারি ও ভাত",
 "Crispy Fish Fry": "মচমচে ফিশ ফ্রাই",
 "Honey Butter Toast": "হানি বাটার টোস্ট",
 "Leafy": "শাকজাতীয়",
 "Roots": "মূলজাতীয়",
 "Everyday": "দৈনন্দিন",
 "Seasonal": "মৌসুমি",
 "Tropical": "ক্রান্তীয়",
 "Meat & Fish": "মাংস ও মাছ",
 "Chicken": "মুরগি",
 "Beef & Mutton": "গরু ও খাসির মাংস",
 "Dairy & Eggs": "দুগ্ধজাত ও ডিম",
 "Milk": "দুধ",
 "Cheese & Butter": "চিজ ও মাখন",
 "Bread": "পাউরুটি",
 "Cakes & Treats": "কেক ও মিষ্টান্ন",
 "Chips": "চিপস",
 "Nuts & Dried": "বাদাম ও শুকনা ফল",
 "Juice": "জুস",
 "Tea & Coffee": "চা ও কফি",
 "Soft Drinks": "সফট ড্রিংকস",
 "Pantry": "মুদি সামগ্রী",
 "Oils": "তেল",
 "Honey & Spreads": "মধু ও স্প্রেড",
 "Basics": "মৌলিক সামগ্রী",
 "Rice & Grains": "চাল ও শস্য",
 "Rice & Flour": "চাল ও আটা",
 "Lentils & Pulses": "ডাল",
 "Frozen Food": "হিমায়িত খাবার",
 "Meals": "তৈরি খাবার",
 "Ice Cream": "আইসক্রিম",
 "Beauty & Care": "বিউটি ও কেয়ার",
 "Skin": "ত্বক",
 "Hair & Body": "চুল ও শরীর",
 "Cleaning": "পরিষ্কার সামগ্রী",
 "Kitchen": "রান্নাঘর",
 "Spices & Masala": "মসলা",
 "Ground": "গুঁড়া",
 "Whole": "গোটা",
 "Noodles & Pasta": "নুডলস ও পাস্তা",
 "Noodles": "নুডলস",
 "Pasta": "পাস্তা",
 "Sweets & Chocolate": "মিষ্টি ও চকলেট",
 "Chocolate": "চকলেট",
 "Candy & Biscuits": "ক্যান্ডি ও বিস্কুট",
 "Breakfast & Cereal": "নাশতা ও সিরিয়াল",
 "Cereal": "সিরিয়াল",
 "Spreads & Mixes": "স্প্রেড ও মিক্স",
 "Baby Care": "শিশুর যত্ন",
 "Feeding": "খাওয়ানো",
 "Bath & Care": "গোসল ও যত্ন",
 "Pet Care": "পোষা প্রাণীর যত্ন",
 "Dogs": "কুকুর",
 "Cats & Others": "বিড়াল ও অন্যান্য",
 "Health & Wellness": "স্বাস্থ্য ও সুস্থতা",
 "Vitamins": "ভিটামিন",
 "Wellness": "সুস্থতা",
 "Personal Hygiene": "ব্যক্তিগত পরিচ্ছন্নতা",
 "Oral Care": "মুখের যত্ন",
 "Body Care": "শরীরের যত্ন",
 "Fresh Farm": "ফ্রেশ ফার্ম",
 "Green Roots": "গ্রিন রুটস",
 "Farm Fresh Meats": "ফার্ম ফ্রেশ মিটস",
 "Sea Catch": "সি ক্যাচ",
 "Dairy Pure": "ডেইরি পিওর",
 "Daily Bake": "ডেইলি বেক",
 "Nut House": "নাট হাউস",
 "Sip Co": "সিপ কো",
 "Golden Grain": "গোল্ডেন গ্রেইন",
 "Spice Route": "স্পাইস রুট",
 "Wok & Co": "ওক অ্যান্ড কো",
 "Choco Bliss": "চকো ব্লিস",
 "Morning Bowl": "মর্নিং বাউল",
 "Little Sprout": "লিটল স্প্রাউট",
 "Pet Pal": "পেট প্যাল",
 "Orchard": "অর্চার্ড",
 "Crispy": "ক্রিস্পি",
 "Bertolli": "বার্তোলি",
 "Sundarban": "সুন্দরবন",
 "Frosty": "ফ্রস্টি",
 "HomeCare": "হোমকেয়ার",
 "VitaWell": "ভিটাওয়েল",
 "PureCare": "পিওরকেয়ার",
 "Tomato": "টমেটো",
 "Spinach Bunch": "পালং শাকের আঁটি",
 "Potato": "আলু",
 "Cucumber": "শসা",
 "Brinjal": "বেগুন",
 "Green Chili": "কাঁচা মরিচ",
 "Red Onion": "লাল পেঁয়াজ",
 "Cauliflower": "ফুলকপি",
 "Sweet Pumpkin": "মিষ্টি কুমড়া",
 "Banana (dozen)": "কলা (ডজন)",
 "Apple": "আপেল",
 "Mango": "আম",
 "Black Grapes": "কালো আঙুর",
 "Papaya": "পেঁপে",
 "Pomegranate": "ডালিম",
 "Watermelon": "তরমুজ",
 "Green Guava": "সবুজ পেয়ারা",
 "Litchi": "লিচু",
 "Broiler Chicken": "ব্রয়লার মুরগি",
 "Chicken Breast": "মুরগির ব্রেস্ট",
 "Chicken Wings": "মুরগির উইংস",
 "Beef (boneless)": "গরুর মাংস (হাড় ছাড়া)",
 "Mutton": "খাসির মাংস",
 "Rohu Fish": "রুই মাছ",
 "Hilsa (Ilish)": "ইলিশ মাছ",
 "Prawn": "চিংড়ি",
 "Tilapia Fish": "তেলাপিয়া মাছ",
 "Fresh Milk 1L": "তাজা দুধ ১ লিটার",
 "Plain Yogurt 500g": "সাদা দই ৫০০ গ্রাম",
 "Fresh Cream 200ml": "ফ্রেশ ক্রিম ২০০ মিলি",
 "Condensed Milk": "কনডেন্সড মিল্ক",
 "Farm Eggs (12)": "খামারের ডিম (১২টি)",
 "Salted Butter 200g": "লবণযুক্ত মাখন ২০০ গ্রাম",
 "Cheese Slices": "চিজ স্লাইস",
 "Paneer 250g": "পনির ২৫০ গ্রাম",
 "Pure Ghee 500g": "খাঁটি ঘি ৫০০ গ্রাম",
 "Sandwich Bread": "স্যান্ডউইচ পাউরুটি",
 "Brown Bread": "ব্রাউন ব্রেড",
 "Croissant (4)": "ক্রোয়াসাঁ (৪টি)",
 "Burger Buns (6)": "বার্গার বান (৬টি)",
 "French Baguette": "ফ্রেঞ্চ ব্যাগেট",
 "Chocolate Cake": "চকলেট কেক",
 "Blueberry Muffins (6)": "ব্লুবেরি মাফিন (৬টি)",
 "Glazed Donuts (4)": "গ্লেজড ডোনাট (৪টি)",
 "Butter Cookies 300g": "বাটার কুকিজ ৩০০ গ্রাম",
 "Potato Chips 150g": "আলুর চিপস ১৫০ গ্রাম",
 "Cheese Crackers": "চিজ ক্র্যাকার",
 "Nacho Chips 200g": "নাচো চিপস ২০০ গ্রাম",
 "Butter Popcorn": "বাটার পপকর্ন",
 "Rice Crisps": "রাইস ক্রিস্প",
 "Whole Cashews 250g": "গোটা কাজুবাদাম ২৫০ গ্রাম",
 "Roasted Almonds 250g": "ভাজা কাঠবাদাম ২৫০ গ্রাম",
 "Pistachios 200g": "পেস্তা বাদাম ২০০ গ্রাম",
 "Raisins 250g": "কিশমিশ ২৫০ গ্রাম",
 "Medjool Dates 500g": "মেজদুল খেজুর ৫০০ গ্রাম",
 "Orange Juice 1L": "কমলার জুস ১ লিটার",
 "Mango Juice 1L": "আমের জুস ১ লিটার",
 "Coconut Water": "ডাবের পানি",
 "Green Tea (25 bags)": "গ্রিন টি (২৫ ব্যাগ)",
 "Black Tea 400g": "কালো চা ৪০০ গ্রাম",
 "Ground Coffee 250g": "গ্রাউন্ড কফি ২৫০ গ্রাম",
 "Instant Coffee Cup": "ইনস্ট্যান্ট কফি কাপ",
 "Cola 1.25L": "কোলা ১.২৫ লিটার",
 "Lemon Soda 500ml": "লেমন সোডা ৫০০ মিলি",
 "Mineral Water 2L": "মিনারেল ওয়াটার ২ লিটার",
 "Olive Oil 500ml": "অলিভ অয়েল ৫০০ মিলি",
 "Mustard Oil 1L": "সরিষার তেল ১ লিটার",
 "Soybean Oil 2L": "সয়াবিন তেল ২ লিটার",
 "Forest Honey 500g": "বনের মধু ৫০০ গ্রাম",
 "Peanut Butter 340g": "পিনাট বাটার ৩৪০ গ্রাম",
 "Strawberry Jam": "স্ট্রবেরি জ্যাম",
 "Sea Salt 500g": "সামুদ্রিক লবণ ৫০০ গ্রাম",
 "Refined Sugar 1kg": "পরিশোধিত চিনি ১ কেজি",
 "Tomato Ketchup": "টমেটো কেচাপ",
 "White Vinegar": "সাদা ভিনেগার",
 "Basmati Rice 5kg": "বাসমতি চাল ৫ কেজি",
 "Miniket Rice 5kg": "মিনিকেট চাল ৫ কেজি",
 "Whole Wheat Flour 2kg": "আটা ২ কেজি",
 "Maida 2kg": "ময়দা ২ কেজি",
 "Oats 500g": "ওটস ৫০০ গ্রাম",
 "Flattened Rice 1kg": "চিড়া ১ কেজি",
 "Red Lentils 1kg": "মসুর ডাল ১ কেজি",
 "Chickpeas 1kg": "ছোলা ১ কেজি",
 "Mung Dal 1kg": "মুগ ডাল ১ কেজি",
 "Black Lentils 1kg": "মাষকলাই ডাল ১ কেজি",
 "Frozen Peas 500g": "হিমায়িত মটরশুঁটি ৫০০ গ্রাম",
 "Sweet Corn 500g": "মিষ্টি ভুট্টা ৫০০ গ্রাম",
 "Chicken Nuggets": "চিকেন নাগেটস",
 "French Fries 1kg": "ফ্রেঞ্চ ফ্রাই ১ কেজি",
 "Frozen Parata (10)": "হিমায়িত পরোটা (১০টি)",
 "Beef Seekh Kebab": "বিফ সিক কাবাব",
 "Vegetable Samosa": "সবজির সিঙ্গারা",
 "Vanilla Ice Cream 1L": "ভ্যানিলা আইসক্রিম ১ লিটার",
 "Chocolate Ice Cream": "চকলেট আইসক্রিম",
 "Mango Kulfi (6)": "আম কুলফি (৬টি)",
 "Face Serum": "ফেস সিরাম",
 "Sunscreen SPF50": "সানস্ক্রিন SPF50",
 "Face Wash": "ফেস ওয়াশ",
 "Clay Face Mask": "ক্লে ফেস মাস্ক",
 "Lip Balm": "লিপ বাম",
 "Body Cream": "বডি ক্রিম",
 "Shampoo 400ml": "শ্যাম্পু ৪০০ মিলি",
 "Conditioner 400ml": "কন্ডিশনার ৪০০ মিলি",
 "Hair Oil 200ml": "হেয়ার অয়েল ২০০ মিলি",
 "Eau de Parfum": "ইউ দ্য পারফিউম",
 "Dish Wash Liquid": "থালা-বাসন ধোয়ার তরল",
 "Laundry Detergent 1kg": "কাপড় ধোয়ার ডিটারজেন্ট ১ কেজি",
 "Floor Cleaner 1L": "ফ্লোর ক্লিনার ১ লিটার",
 "Toilet Cleaner": "টয়লেট ক্লিনার",
 "Glass Cleaner": "গ্লাস ক্লিনার",
 "Bleach 1L": "ব্লিচ ১ লিটার",
 "Paper Towels (2)": "পেপার টাওয়েল (২টি)",
 "Garbage Bags (30)": "ময়লার ব্যাগ (৩০টি)",
 "Kitchen Sponge (3)": "কিচেন স্পঞ্জ (৩টি)",
 "Air Freshener": "এয়ার ফ্রেশনার",
 "Turmeric Powder 200g": "হলুদ গুঁড়া ২০০ গ্রাম",
 "Chili Powder 200g": "মরিচ গুঁড়া ২০০ গ্রাম",
 "Cumin Powder 100g": "জিরা গুঁড়া ১০০ গ্রাম",
 "Coriander Powder": "ধনে গুঁড়া",
 "Garam Masala 100g": "গরম মসলা ১০০ গ্রাম",
 "Biryani Masala": "বিরিয়ানি মসলা",
 "Black Pepper 100g": "গোলমরিচ ১০০ গ্রাম",
 "Cinnamon Sticks": "দারুচিনি",
 "Green Cardamom 50g": "এলাচ ৫০ গ্রাম",
 "Bay Leaves": "তেজপাতা",
 "Instant Noodles (5)": "ইনস্ট্যান্ট নুডলস (৫টি)",
 "Cup Noodles": "কাপ নুডলস",
 "Egg Noodles 400g": "ডিমের নুডলস ৪০০ গ্রাম",
 "Rice Noodles 400g": "রাইস নুডলস ৪০০ গ্রাম",
 "Ramen Pack (3)": "রামেন প্যাক (৩টি)",
 "Spaghetti 500g": "স্প্যাগেটি ৫০০ গ্রাম",
 "Penne Pasta 500g": "পেনে পাস্তা ৫০০ গ্রাম",
 "Macaroni 400g": "ম্যাকারনি ৪০০ গ্রাম",
 "Vermicelli 400g": "সেমাই ৪০০ গ্রাম",
 "Pasta Sauce 350g": "পাস্তা সস ৩৫০ গ্রাম",
 "Dark Chocolate Bar": "ডার্ক চকলেট বার",
 "Milk Chocolate Bar": "মিল্ক চকলেট বার",
 "Hazelnut Spread": "হ্যাজেলনাট স্প্রেড",
 "Chocolate Truffles": "চকলেট ট্রাফল",
 "Cocoa Powder 200g": "কোকো পাউডার ২০০ গ্রাম",
 "Gummy Bears": "গামি বিয়ার",
 "Fruit Candy Mix": "ফ্রুট ক্যান্ডি মিক্স",
 "Cream Biscuits": "ক্রিম বিস্কুট",
 "Chocolate Wafer": "চকলেট ওয়েফার",
 "Rasgulla Tin 1kg": "রসগোল্লা টিন ১ কেজি",
 "Corn Flakes 500g": "কর্ন ফ্লেক্স ৫০০ গ্রাম",
 "Choco Pillows": "চকো পিলো",
 "Muesli 500g": "মুসলি ৫০০ গ্রাম",
 "Honey Granola": "হানি গ্রানোলা",
 "Cereal Bars (6)": "সিরিয়াল বার (৬টি)",
 "Instant Porridge": "ইনস্ট্যান্ট পরিজ",
 "Pancake Mix 500g": "প্যানকেক মিক্স ৫০০ গ্রাম",
 "Maple Syrup": "ম্যাপল সিরাপ",
 "Mixed Fruit Jam": "মিক্সড ফ্রুট জ্যাম",
 "Chia Seeds 250g": "চিয়া সিড ২৫০ গ্রাম",
 "Infant Formula 400g": "শিশুর ফর্মুলা ৪০০ গ্রাম",
 "Baby Cereal 250g": "বেবি সিরিয়াল ২৫০ গ্রাম",
 "Feeding Bottle": "ফিডিং বোতল",
 "Fruit Puree Pouch": "ফ্রুট পিউরি পাউচ",
 "Baby Diapers (M, 40)": "বেবি ডায়াপার (M, ৪০টি)",
 "Baby Wipes (80)": "বেবি ওয়াইপস (৮০টি)",
 "Baby Lotion": "বেবি লোশন",
 "Baby Shampoo": "বেবি শ্যাম্পু",
 "Baby Powder": "বেবি পাউডার",
 "Rash Cream": "র‍্যাশ ক্রিম",
 "Dog Food 3kg": "কুকুরের খাবার ৩ কেজি",
 "Puppy Food 1.5kg": "কুকুরছানার খাবার ১.৫ কেজি",
 "Dog Chew Treats": "কুকুরের চিবানোর ট্রিট",
 "Pet Shampoo": "পোষা প্রাণীর শ্যাম্পু",
 "Dog Biscuits": "কুকুরের বিস্কুট",
 "Cat Food 1.5kg": "বিড়ালের খাবার ১.৫ কেজি",
 "Kitten Wet Food": "বিড়ালছানার ভেজা খাবার",
 "Cat Litter 5kg": "ক্যাট লিটার ৫ কেজি",
 "Fish Food 100g": "মাছের খাবার ১০০ গ্রাম",
 "Bird Seed Mix": "পাখির খাবার মিক্স",
 "Vitamin C 500mg": "ভিটামিন সি ৫০০ মিগ্রা",
 "Multivitamin (60)": "মাল্টিভিটামিন (৬০টি)",
 "Omega-3 Fish Oil": "ওমেগা-৩ ফিশ অয়েল",
 "Vitamin D3": "ভিটামিন ডি৩",
 "Calcium + Zinc": "ক্যালসিয়াম + জিংক",
 "Whey Protein 1kg": "হুই প্রোটিন ১ কেজি",
 "Herbal Tea Mix": "হার্বাল টি মিক্স",
 "ORS Saline (10)": "খাবার স্যালাইন (১০টি)",
 "Hand Sanitizer": "হ্যান্ড স্যানিটাইজার",
 "Digital Thermometer": "ডিজিটাল থার্মোমিটার",
 "Toothpaste 150g": "টুথপেস্ট ১৫০ গ্রাম",
 "Charcoal Toothpaste": "চারকোল টুথপেস্ট",
 "Toothbrush (2)": "টুথব্রাশ (২টি)",
 "Mouthwash 500ml": "মাউথওয়াশ ৫০০ মিলি",
 "Cotton Buds (200)": "কটন বাডস (২০০টি)",
 "Beauty Soap (4)": "বিউটি সাবান (৪টি)",
 "Hand Wash Refill": "হ্যান্ড ওয়াশ রিফিল",
 "Deodorant Spray": "ডিওডোরেন্ট স্প্রে",
 "Tissue Box (3)": "টিস্যু বক্স (৩টি)",
 "Razor Pack (3)": "রেজর প্যাক (৩টি)",
 "Carrot": "গাজর",
 "Orange": "কমলা",
 "Beef Mince": "গরুর কিমা",
 "Brown Eggs (6)": "বাদামি ডিম (৬টি)",
 "Vanilla Cupcakes (4)": "ভ্যানিলা কাপকেক (৪টি)",
 "Very fresh and good quality. Will order again.": "খুব তাজা ও ভালো মানের। আবার অর্ডার করব।",
 "Exactly as described. Packing was perfect.": "যেমন বলা হয়েছিল ঠিক তেমনই। প্যাকিং চমৎকার ছিল।",
 "Best price for this quality. Highly recommended!": "এই মানের জন্য সেরা দাম। অবশ্যই সুপারিশ করব!",
 "Delivered fast and everything was in good condition.": "দ্রুত ডেলিভারি পেয়েছি, সবকিছু ভালো অবস্থায় ছিল।",
 "Excellent! My family loved it.": "অসাধারণ! আমার পরিবারের খুব পছন্দ হয়েছে।",
 "Top quality, much better than the local shop.": "সেরা মান, স্থানীয় দোকানের চেয়ে অনেক ভালো।",
 "Good quality and fair price.": "ভালো মান ও ন্যায্য দাম।",
 "Nice product, packing could be a little better.": "ভালো পণ্য, প্যাকিং আরেকটু ভালো হতে পারত।",
 "Fresh and tasty. Delivery was on time.": "তাজা ও সুস্বাদু। ডেলিভারি সময়মতো হয়েছে।",
 "Happy with it. Will buy again.": "সন্তুষ্ট। আবার কিনব।",
 "Worth the money.": "টাকার মূল্য পেয়েছি।",
 "Okay for the price. Nothing special.": "দামের তুলনায় মোটামুটি। বিশেষ কিছু না।",
 "Average quality, but delivery was quick.": "মান মাঝারি, তবে ডেলিভারি দ্রুত ছিল।",
 "Some pieces were not so fresh, rest was fine.": "কিছু অংশ তেমন তাজা ছিল না, বাকিটা ঠিক ছিল।",
 "Quality was below my expectation.": "মান আমার প্রত্যাশার চেয়ে কম ছিল।",
 "Packing was poor and the quantity felt less.": "প্যাকিং খারাপ ছিল এবং পরিমাণ কম মনে হয়েছে।",
 "Not fresh at all. Disappointed.": "একদমই তাজা না। হতাশ।",
 "Did not match the photo. Would not order again.": "ছবির সঙ্গে মেলেনি। আর অর্ডার করব না।",
 "R": "র",
 "K": "ক",
 "N": "ন",
 "T": "ত",
 "S": "স",
 "F": "ফ",
 "I": "ই",
 "M": "ম",
 "J": "জ",
 "H": "হ",
 "A": "আ",
 "L": "ল"
};

export const REVIEW_FIRST = {"Rahim": "রহিম", "Karim": "করিম", "Nusrat": "নুসরাত", "Tania": "তানিয়া", "Sabbir": "সাব্বির", "Farhana": "ফারহানা", "Imran": "ইমরান", "Mim": "মিম", "Rakib": "রাকিব", "Sumaiya": "সুমাইয়া", "Tanvir": "তানভীর", "Jannat": "জান্নাত", "Hasan": "হাসান", "Nabila": "নাবিলা", "Arif": "আরিফ", "Shirin": "শিরিন", "Mahin": "মাহিন", "Sadia": "সাদিয়া", "Rubel": "রুবেল", "Tasnim": "তাসনিম", "Shakil": "শাকিল", "Lamia": "লামিয়া", "Nayeem": "নাঈম", "Ritu": "ঋতু"};
export const REVIEW_INITIAL = {"U": "উ", "A": "আ", "H": "হো", "K": "খা", "I": "ই", "R": "র", "C": "চৌ", "B": "বে", "S": "স", "M": "মি", "D": "দা"};

// set by bnPhrases.js so patterns can translate product names / slot labels inside a sentence
let LOOK = {};
export const setLookup = (p) => { LOOK = p; };
const tn = (s) => (Object.prototype.hasOwnProperty.call(LOOK, s) ? LOOK[s] : s);

export const MORE_PATTERNS = [
  [/^Up to (\d+)% off$/, (n) => `${n}% পর্যন্ত ছাড়`],
  [/^Only (\d+) Left$/, (n) => `মাত্র ${n}টি আছে`],
  [/^([A-Z][a-z]+) ([A-Z])\.$/, (f, i) => (REVIEW_FIRST[f] && REVIEW_INITIAL[i] ? `${REVIEW_FIRST[f]} ${REVIEW_INITIAL[i]}.` : `${f} ${i}.`)],
  [/^(.+) is out of stock\. Please remove it from your cart\.$/, (n) => `${tn(n)} স্টকে নেই। কার্ট থেকে সরিয়ে দিন।`],
  [/^Only (\d+) of (.+) available\.$/, (q, n) => `${tn(n)} মাত্র ${q}টি আছে।`],
  [/^Time slots: (.+)\. Express delivery \(within ~90 minutes\) is available in selected areas for an extra charge\.$/, (l) => `সময় স্লট: ${l.split(", ").map(tn).join(", ")}। নির্বাচিত এলাকায় অতিরিক্ত চার্জে এক্সপ্রেস ডেলিভারি (~৯০ মিনিটের মধ্যে) পাওয়া যায়।`],
  [/^Free delivery on orders of (৳\s?[\d,]+) or more \(Standard delivery\)\.$/, (a) => `${a} বা তার বেশি অর্ডারে ফ্রি ডেলিভারি (স্ট্যান্ডার্ড ডেলিভারি)।`],
  [/^Return requested · (.+)$/, (r) => `রিটার্নের অনুরোধ করা হয়েছে · ${r}`],
];
