 // Central place for ALL dummy image URLs. Swap any of these for your database / API image URL later:
// just set `image` (and optionally `fallback`) on the item in data.js, or replace these helpers.
//
//  1) Unsplash CDN: only photo ids that were checked on unsplash.com (UNSPLASH_* below)
//  2) Everything else: keyword photo from LoremFlickr (free, always returns a real photo for the keyword;
//     `?lock=N` keeps the same picture every time)
//  3) If an image still fails in the browser, Art.js tries `fallback`, then a plain tinted tile.

export const unsplash = (id, w, h) => `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=${w}&h=${h}&q=80`;
export const flickr = (keyword, lock, w, h) => `https://loremflickr.com/${w}/${h}/${keyword}?lock=${lock}`;

const UNSPLASH_PRODUCTS = {
 "Tomato": "1587334274535-5f82e7e55dc0"
};
const UNSPLASH_CATEGORIES = {
 "veg": "1518977822534-7049a61ee0c2"
};
const UNSPLASH_BANNERS = {
 "c3": "1513791053024-3b50799fdd7b"
};

const PRODUCT_KEYWORDS = {
 "Tomato": "tomato",
 "Spinach Bunch": "spinach",
 "Carrot": "carrot",
 "Potato": "potato",
 "Cucumber": "cucumber",
 "Brinjal": "eggplant",
 "Green Chili": "chili",
 "Red Onion": "onion",
 "Cauliflower": "cauliflower",
 "Sweet Pumpkin": "pumpkin",
 "Banana (dozen)": "banana",
 "Apple": "apple",
 "Mango": "mango",
 "Orange": "orange",
 "Black Grapes": "grapes",
 "Papaya": "papaya",
 "Pomegranate": "pomegranate",
 "Watermelon": "watermelon",
 "Green Guava": "guava",
 "Litchi": "lychee",
 "Broiler Chicken": "chicken",
 "Chicken Breast": "chickenbreast",
 "Chicken Wings": "chickenwings",
 "Beef (boneless)": "beef",
 "Beef Mince": "mincedmeat",
 "Mutton": "lamb",
 "Rohu Fish": "fish",
 "Hilsa (Ilish)": "herring",
 "Prawn": "prawn",
 "Tilapia Fish": "seafood",
 "Fresh Milk 1L": "milk",
 "Plain Yogurt 500g": "yogurt",
 "Fresh Cream 200ml": "cream",
 "Condensed Milk": "dairy",
 "Farm Eggs (12)": "eggs",
 "Brown Eggs (6)": "egg",
 "Salted Butter 200g": "butter",
 "Cheese Slices": "cheese",
 "Paneer 250g": "paneer",
 "Pure Ghee 500g": "ghee",
 "Sandwich Bread": "bread",
 "Brown Bread": "wholewheat",
 "Croissant (4)": "croissant",
 "Burger Buns (6)": "bun",
 "French Baguette": "baguette",
 "Chocolate Cake": "chocolatecake",
 "Vanilla Cupcakes (4)": "cupcake",
 "Blueberry Muffins (6)": "muffin",
 "Glazed Donuts (4)": "donut",
 "Butter Cookies 300g": "cookies",
 "Potato Chips 150g": "chips",
 "Cheese Crackers": "crackers",
 "Nacho Chips 200g": "nachos",
 "Butter Popcorn": "popcorn",
 "Rice Crisps": "ricecracker",
 "Whole Cashews 250g": "cashew",
 "Roasted Almonds 250g": "almonds",
 "Pistachios 200g": "pistachio",
 "Raisins 250g": "raisins",
 "Medjool Dates 500g": "dates",
 "Orange Juice 1L": "orangejuice",
 "Mango Juice 1L": "juice",
 "Coconut Water": "coconut",
 "Green Tea (25 bags)": "greentea",
 "Black Tea 400g": "tea",
 "Ground Coffee 250g": "coffee",
 "Instant Coffee Cup": "coffeecup",
 "Cola 1.25L": "cola",
 "Lemon Soda 500ml": "lemonade",
 "Mineral Water 2L": "water",
 "Olive Oil 500ml": "oliveoil",
 "Mustard Oil 1L": "mustard",
 "Soybean Oil 2L": "cookingoil",
 "Forest Honey 500g": "honey",
 "Peanut Butter 340g": "peanutbutter",
 "Strawberry Jam": "jam",
 "Sea Salt 500g": "salt",
 "Refined Sugar 1kg": "sugar",
 "Tomato Ketchup": "ketchup",
 "White Vinegar": "vinegar",
 "Basmati Rice 5kg": "rice",
 "Miniket Rice 5kg": "grain",
 "Whole Wheat Flour 2kg": "flour",
 "Maida 2kg": "wheat",
 "Oats 500g": "oats",
 "Flattened Rice 1kg": "cereal",
 "Red Lentils 1kg": "lentils",
 "Chickpeas 1kg": "chickpeas",
 "Mung Dal 1kg": "beans",
 "Black Lentils 1kg": "legumes",
 "Frozen Peas 500g": "peas",
 "Sweet Corn 500g": "corn",
 "Chicken Nuggets": "nuggets",
 "French Fries 1kg": "fries",
 "Frozen Parata (10)": "paratha",
 "Beef Seekh Kebab": "kebab",
 "Vegetable Samosa": "samosa",
 "Vanilla Ice Cream 1L": "icecream",
 "Chocolate Ice Cream": "gelato",
 "Mango Kulfi (6)": "popsicle",
 "Face Serum": "serum",
 "Sunscreen SPF50": "sunscreen",
 "Face Wash": "facewash",
 "Clay Face Mask": "facemask",
 "Lip Balm": "lipbalm",
 "Body Cream": "moisturizer",
 "Shampoo 400ml": "shampoo",
 "Conditioner 400ml": "haircare",
 "Hair Oil 200ml": "hairoil",
 "Eau de Parfum": "perfume",
 "Dish Wash Liquid": "dishsoap",
 "Laundry Detergent 1kg": "laundry",
 "Floor Cleaner 1L": "cleaning",
 "Toilet Cleaner": "cleaningproducts",
 "Glass Cleaner": "spraybottle",
 "Bleach 1L": "detergent",
 "Paper Towels (2)": "papertowel",
 "Garbage Bags (30)": "trashbag",
 "Kitchen Sponge (3)": "sponge",
 "Air Freshener": "airfreshener",
 "Turmeric Powder 200g": "turmeric",
 "Chili Powder 200g": "chilipowder",
 "Cumin Powder 100g": "cumin",
 "Coriander Powder": "coriander",
 "Garam Masala 100g": "spices",
 "Biryani Masala": "masala",
 "Black Pepper 100g": "blackpepper",
 "Cinnamon Sticks": "cinnamon",
 "Green Cardamom 50g": "cardamom",
 "Bay Leaves": "bayleaf",
 "Instant Noodles (5)": "noodles",
 "Cup Noodles": "ramen",
 "Egg Noodles 400g": "eggnoodles",
 "Rice Noodles 400g": "ricenoodles",
 "Ramen Pack (3)": "ramenbowl",
 "Spaghetti 500g": "spaghetti",
 "Penne Pasta 500g": "penne",
 "Macaroni 400g": "macaroni",
 "Vermicelli 400g": "vermicelli",
 "Pasta Sauce 350g": "tomatosauce",
 "Dark Chocolate Bar": "darkchocolate",
 "Milk Chocolate Bar": "chocolate",
 "Hazelnut Spread": "hazelnut",
 "Chocolate Truffles": "truffle",
 "Cocoa Powder 200g": "cocoa",
 "Gummy Bears": "gummybears",
 "Fruit Candy Mix": "candy",
 "Cream Biscuits": "biscuits",
 "Chocolate Wafer": "wafer",
 "Rasgulla Tin 1kg": "sweets",
 "Corn Flakes 500g": "cornflakes",
 "Choco Pillows": "breakfastcereal",
 "Muesli 500g": "muesli",
 "Honey Granola": "granola",
 "Cereal Bars (6)": "granolabar",
 "Instant Porridge": "porridge",
 "Pancake Mix 500g": "pancakes",
 "Maple Syrup": "maplesyrup",
 "Mixed Fruit Jam": "marmalade",
 "Chia Seeds 250g": "chiaseeds",
 "Infant Formula 400g": "babyformula",
 "Baby Cereal 250g": "babyfood",
 "Feeding Bottle": "babybottle",
 "Fruit Puree Pouch": "puree",
 "Baby Diapers (M, 40)": "diaper",
 "Baby Wipes (80)": "babywipes",
 "Baby Lotion": "babylotion",
 "Baby Shampoo": "babybath",
 "Baby Powder": "babypowder",
 "Rash Cream": "babycare",
 "Dog Food 3kg": "dogfood",
 "Puppy Food 1.5kg": "puppy",
 "Dog Chew Treats": "dogtreats",
 "Pet Shampoo": "dogbath",
 "Dog Biscuits": "dogbiscuit",
 "Cat Food 1.5kg": "catfood",
 "Kitten Wet Food": "kitten",
 "Cat Litter 5kg": "cat",
 "Fish Food 100g": "aquarium",
 "Bird Seed Mix": "birdseed",
 "Vitamin C 500mg": "vitamin",
 "Multivitamin (60)": "supplements",
 "Omega-3 Fish Oil": "fishoil",
 "Vitamin D3": "capsules",
 "Calcium + Zinc": "pills",
 "Whey Protein 1kg": "protein",
 "Herbal Tea Mix": "herbaltea",
 "ORS Saline (10)": "electrolyte",
 "Hand Sanitizer": "sanitizer",
 "Digital Thermometer": "thermometer",
 "Toothpaste 150g": "toothpaste",
 "Charcoal Toothpaste": "toothbrush",
 "Toothbrush (2)": "toothbrushes",
 "Mouthwash 500ml": "mouthwash",
 "Cotton Buds (200)": "cottonbuds",
 "Beauty Soap (4)": "soap",
 "Hand Wash Refill": "handwash",
 "Deodorant Spray": "deodorant",
 "Tissue Box (3)": "tissue",
 "Razor Pack (3)": "razor"
};
const CATEGORY_KEYWORDS = {
 "veg": "vegetables",
 "fruits": "fruit",
 "meat": "meat",
 "dairy": "dairy",
 "bakery": "bakery",
 "snacks": "snacks",
 "drinks": "beverage",
 "pantry": "pantry",
 "grains": "grains",
 "frozen": "frozen",
 "beauty": "skincare",
 "home": "cleaning",
 "spices": "spices",
 "noodles": "pasta",
 "sweets": "chocolate",
 "breakfast": "breakfast",
 "baby": "baby",
 "pet": "pet",
 "health": "vitamins",
 "hygiene": "hygiene"
};
const BANNER_KEYWORDS = {
 "c1": "feast,spices",
 "c2": "skincare,beauty",
 "c3": "market,vegetables",
 "c4": "chocolate,dessert"
};

// Your own product photos (public/products/<file>.jpg). Add a line here to use a local photo for any product name.
const LOCAL_PRODUCT_PHOTOS = {
  "Face Serum": "/products/face-serum.jpg",
  "Body Cream": "/products/body-cream.jpg",
  "Eau de Parfum": "/products/eau-de-parfum.jpg",
  "Face Wash": "/products/face-wash.jpg",
  "Clay Face Mask": "/products/clay-face-mask.jpg",
  // Popular picks
  "Carrot": "/products/carrot.jpg",
  "Orange": "/products/orange.jpg",
  "Beef Mince": "/products/beef-mince.jpg",
  "Brown Eggs (6)": "/products/brown-eggs.jpg",
  // Quick reorder
  "Fresh Milk 1L": "/products/fresh-milk.jpg",
  "Farm Eggs (12)": "/products/farm-eggs.jpg",
  "Tomato": "/products/tomato.jpg",
  // Vegetables (your own photos)
  "Spinach Bunch": "/products/spinach-bunch.jpg",
  "Potato": "/products/potato.jpg",
  "Cucumber": "/products/cucumber.jpg",
  "Brinjal": "/products/brinjal.jpg",
  "Green Chili": "/products/green-chili.jpg",
  "Red Onion": "/products/red-onion.jpg",
  "Cauliflower": "/products/cauliflower.jpg",
  "Sweet Pumpkin": "/products/sweet-pumpkin.jpg",
  "Banana (dozen)": "/products/banana.jpg",
  "Vanilla Cupcakes (4)": "/products/vanilla-cupcakes.jpg",
};
export const productImage = (name, id) => (LOCAL_PRODUCT_PHOTOS[name] ? LOCAL_PRODUCT_PHOTOS[name] : UNSPLASH_PRODUCTS[name] ? unsplash(UNSPLASH_PRODUCTS[name], 480, 480) : flickr(PRODUCT_KEYWORDS[name] || "grocery", id, 480, 480));
export const productFallback = (category, id) => flickr(CATEGORY_KEYWORDS[category] || "grocery", id + 500, 480, 480);
// The first 8 categories use your own photos from public/categories/<id>.jpg (replace a file to change it).
const LOCAL_CATEGORY_PHOTOS = ["veg", "fruits", "meat", "dairy", "bakery", "snacks", "drinks", "pantry"];
export const categoryImage = (id) => (LOCAL_CATEGORY_PHOTOS.includes(id) ? `/categories/${id}.jpg` : UNSPLASH_CATEGORIES[id] ? unsplash(UNSPLASH_CATEGORIES[id], 320, 320) : flickr(CATEGORY_KEYWORDS[id] || "grocery", 900 + id.length, 320, 320));
export const categoryFallback = (id) => flickr("grocery", 950 + id.length, 320, 320);
export const bannerImage = (id) => (UNSPLASH_BANNERS[id] ? unsplash(UNSPLASH_BANNERS[id], 1600, 640) : flickr(BANNER_KEYWORDS[id], 77, 1600, 640));
export const bannerFallback = (id) => flickr("grocery,market", 88, 1600, 640);